export const PanelStateConstant: any = {
    'txCapture': 'txCapture',
    'txVerify': 'txVerify',
    'txConfirm': 'txConfirm'
};

export const ACCOUNTFILTER: any = {
    'DOMESTIC_TRANSFER_TO': 'DOMESTIC_TRANSFER_TO',
    'DOMESTIC_TRANSFER_FROM': 'DOMESTIC_TRANSFER_FROM',
    'BILL_PAYMENT': 'BILL_PAYMENT',
    'DOMESTIC_PAYMENT_OTHER_BANK': 'DOMESTIC_PAYMENT_OTHER_BANK',
    'DOMESTIC_PAYMENT_HSBC': 'DOMESTIC_PAYMENT_HSBC',
    'INTERNATIONAL_TRANSFER_TO': 'INTERNATIONAL_TRANSFER_TO',
    'INTERNATIONAL_TRANSFER_FROM': 'INTERNATIONAL_TRANSFER_FROM'
};
